trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
    - script: dotnet build --configuration $(buildConfuguration)
      displayName: 'dotnet build $(buildConfuguration)'